package:
  name: vector
  version: 0.42.0
  epoch: 1
  description: End-to-end observability data pipeline
  copyright:
    - license: MPL-2.0
  resources:
    cpu: 16
    memory: 24Gi

environment:
  contents:
    packages:
      - bash
      - build-base
      - cyrus-sasl-dev
      - librdkafka
      - librdkafka-dev
      - openssf-compiler-options
      - openssl
      - openssl-dev
      - perl
      - pkgconf-dev
      - protobuf-dev
      - rust
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/vectordotdev/vector
      tag: v${{package.version}}
      expected-commit: 3d16e345232bb3cb9b104ee6461e9dd0b4c361da

  - runs: |
      sed -i '7s/deny/allow/' src/lib.rs
      export RUSTFLAGS="$RUSTFLAGS --cap-lints=warn"
      make build

  - runs: |
      install -Dm755 target/release/vector "${{targets.destdir}}"/usr/bin/vector
      mkdir -p "${{targets.destdir}}"/etc/vector
      cp config/vector.yaml "${{targets.destdir}}"/etc/vector/vector.yaml

  - uses: strip

update:
  enabled: true
  github:
    identifier: vectordotdev/vector
    strip-prefix: v

test:
  environment:
    contents:
      packages:
        - musl

  pipeline:                                                                                                                 
    - name: Check vector version
      runs: |
        vector --version

    - name: Run a basic vector configuration
      runs: |
        echo 'data_dir = "/tmp/vector"' > /tmp/vector.toml
        echo '[sources.my_source]' >> /tmp/vector.toml
        echo 'type = "stdin"' >> /tmp/vector.toml                                                                           
        echo '[sinks.my_sink]' >> /tmp/vector.toml                                                                          
        echo 'type = "console"' >> /tmp/vector.toml                                                                         
        echo 'inputs = ["my_source"]' >> /tmp/vector.toml
        vector --config /tmp/vector.toml --dry-run

